services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    ports:
      - 8080:8080

volumes:
  postgres:
